### ISSUE TITLE
ping does not work

### ISSUE THREAD

**Issue by waywardmonkeys** [derekjw/fyrie-redis#7]
net.fyrie.redis.RedisProtocolException: Unexpected response
    at net.fyrie.redis.Commands$$anonfun$19.apply(RedisClient.scala:391)
    at net.fyrie.redis.Commands$$anonfun$19.apply(RedisClient.scala:388)
    at net.fyrie.redis.RedisClientSync$class.resultAsOkStatus(RedisClient.scala:113)
    at net.fyrie.redis.RedisClient$$anon$1.resultAsOkStatus(RedisClient.scala:33)
    at net.fyrie.redis.RedisClient$$anon$1.resultAsOkStatus(RedisClient.scala:33)
    at net.fyrie.redis.commands.Keys$class.ping(Keys.scala:197)
    at net.fyrie.redis.RedisClient$$anon$1.ping(RedisClient.scala:33)
    at com.direwolfdigital.dwdCoreServices.core.storage.RedisHealthCheck.check(RedisStorage.scala:18)
    at com.yammer.metrics.core.HealthCheck.execute(HealthCheck.java:52)
    at com.yammer.metrics.HealthChecks.runHealthChecks(HealthChecks.java:37)
    at com.yammer.metrics.reporting.MetricsServlet.handleHealthCheck(MetricsServlet.java:125)
    at com.yammer.metrics.reporting.MetricsServlet.doGet(MetricsServlet.java:108)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:538)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:478)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:937)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:871)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
    at org.eclipse.jetty.server.Server.handle(Server.java:346)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:589)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1048)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:601)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:214)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:411)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:535)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:529)
    at java.lang.Thread.run(Thread.java:680)

**Comment by waywardmonkeys** [comment]
That's because it should return a string "PONG" but you have it returning Unit, I think.

**Comment by derekjw** [comment]
Yeah, I return Unit for commands that return "OK". I forgot PING is different. Fixed now. Thanks.
